export const FETCH_CHARACTER = 'people/FETCH_CHARACTER';
export const FETCH_CHARACTER_SUCCESS = 'people/FETCH_CHARACTER_SUCCESS';
export const FETCH_CHARACTER_FAILURE = 'people/FETCH_CHARACTER_FAILURE';
export const FETCH_PEOPLE_LIST = 'people/FETCH_PEOPLE_LIST';
export const FETCH_PEOPLE_LIST_SUCCESS = 'people/FETCH_PEOPLE_LIST_SUCCESS';
export const FETCH_PEOPLE_LIST_FAILURE = 'people/FETCH_PEOPLE_LIST_FAILURE';